---
- name: Log into a personal DockerHub
  become: yes
  docker_login:
    username: '{{ dockerhub_username }}'
    password: '{{ dockerhub_password }}'


- name: Pull an image called test
  become: yes
  docker_image:
    name: '{{ dockerhub_pulling_image }}'
    source: pull
    

   

  



