version: '3.7'

services:
  frondend:
    container_name: frondend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '.:/app/node_modules'
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true