version: '3.7'

services:

  frondend:
    container_name: frondend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      # - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - REACT_APP_CCC_API=xxxxxxx:5000