# OpenStack
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    # - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    #  - role: openstack-volume-snapshot

# Docker Couchdb
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./ada.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-proxy
    - role: docker-configuration-couchdb
    - role: docker-installation
    - role: docker-proxy
    - role: docker-pull-image-couchdb
    - role: docker-create-container-couchdb
    - role: couchdb-setup

# Couchdb run
# - hosts: "{{groups['all'][0]}}"
#   gather_facts: true
#   roles:
#     - role: couchdb-run-crawler

# Couchdb build
# - hosts: localhost
#   vars_files:
#     - host_vars/mrc.yaml
#   gather_facts: true
#   roles:
#    - role: couchdb-build-replicate