---

- name: Copy Crawler to Instance
  become: yes
  copy:
    src: ../crawler
    dest: /home/ubuntu
    mode: u=rw

- name: Install dependencies
  tags: 'python'
  become: yes
  apt:
    name: ['curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools']
    state: latest
    install_recommends: no
    update_cache: yes


- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker']
    state: latest


- name: Start streaming_to_couchdb.py using Docker Compose
  become: yes
  environment: "{{ env_vars }}"
  docker_compose:
    project_src: "/home/ubuntu/crawler/"
    build: yes
    remove_orphans: yes
    remove_volumes: yes
    recreate: always

- debug:
    msg: "Remote node {{ groups['all'][0]  }} is running streaming_to_couchdb.py on the background."
