---
- name: Check if couchdb is created
  become: yes
  uri:
    url: http://127.0.0.1:5984


- debug: 
    msg: "Couchdb is established"



- name: create a database "tweets"
  become: yes
  uri:
    url: http://{{couchdb_user}}:{{couchdb_password}}@localhost:5984/tweets
    method: PUT
    force_basic_auth: yes
    status_code: 201,412




- debug: 
    msg: "A database called tweets is created"



- name: Copy design.json from local to remote hosts
  become: yes
  copy:
    src: design.json
    dest: /home/ubuntu/
    mode: u=rw

- name: Copy streamCrawler.py from local to remote hosts
  become: yes
  copy:
    src: streamCrawler.py
    dest: /home/ubuntu/
    mode: u=rw


- name: Create design document
  become: yes
  shell: curl -X PUT http://{{ couchdb_user }}:{{ couchdb_password }}@127.0.0.1:5984/tweets/_design/abc --data-binary @design.json










