---
- hosts: localhost
  gather_facts: true

  roles:
    - role: add-ada

# Docker Couchdb
- hosts: couch
  vars_files:
    - host_vars/work.yaml
    - host_vars/workremote.yaml
  gather_facts: true

  roles:
    - role: openstack-proxy
    - role: docker-configuration-couchdb
    - role: docker-installation
    - role: docker-proxy
    - role: docker-create-network
    - role: docker-pull-image-couchdb
    - role: docker-create-container-couchdb
    - role: couchdb-setup
    - role: deploy