---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/openstack.yaml
  gather_facts: true


  roles:
    # - role: openstack-common
    - role: remove-instances
    - role: remove-volumes
    - role: remove-security-groups