---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/work.yaml
    - host_vars/workremote.yaml
  gather_facts: true


  roles:
    - role: remove-instances
    - role: remove-volumes
    - role: remove-security-groups