---
- hosts: localhost
  gather_facts: true

  roles:
    - role: add-ada

# Docker
- hosts: instance3
  vars_files:
    - host_vars/mrc2.yaml
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - role: openstack-proxy
    - role: docker-configuration-couchdb
    - role: docker-installation
    - role: docker-proxy
    - role: docker-create-network
    - role: deploy
