---
- hosts: localhost
  gather_facts: true

  roles:
    - role: add-ada

# Docker Couchdb
- hosts: instances
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - role: openstack-proxy
    - role: docker-configuration-couchdb
    - role: docker-installation
    - role: docker-proxy
    - role: docker-pull-image-couchdb
    - role: docker-create-container-couchdb
    - role: couchdb-setup

# Couchdb run
# - hosts: "{{groups['all'][0]}}"
#   gather_facts: true
#   roles:
#     - role: couchdb-run-crawler

# Couchdb build
# - hosts: localhost
#   vars_files:
#     - host_vars/openstack.yaml
#   gather_facts: true
#   roles:
#    - role: couchdb-build-replicate